-- ============================================================
-- US Financial Loan Monitoring System
-- Script:   03_data_ingestion.sql
-- Platform: Microsoft SQL Server 2019+
-- Tool:     SSMS or sqlcmd
-- Purpose:  Load the Python-generated CSV files into SQL Server
--           and populate the monthly delinquency snapshot table
--
-- Run order: After 01_create_schema.sql
-- Requires:  data/processed/loan_portfolio.csv
--            data/processed/loan_portfolio_scored.csv
-- ============================================================

USE loan_risk_db;
GO


-- ── Step 1: Load loan_portfolio from CSV ──────────────────────
-- Update the file path to match the location on your machine.
-- Use the full Windows path with backslashes.
-- The SQL Server service account must have READ access to the folder.

BULK INSERT loan_portfolio
FROM 'C:\Projects\us-financial-loan-monitoring\data\processed\loan_portfolio.csv'
WITH (
    FORMAT          = 'CSV',
    FIRSTROW        = 2,          -- row 1 is the header
    FIELDTERMINATOR = ',',
    ROWTERMINATOR   = '\n',
    TABLOCK
);
GO


-- ── Step 2: Load loan_risk_scores from CSV ────────────────────
-- This file is generated by python/03_default_prediction.py
-- It contains the model PD score for every loan.

BULK INSERT loan_risk_scores (loan_id, model_pd, risk_band)
FROM 'C:\Projects\us-financial-loan-monitoring\data\processed\loan_portfolio_scored.csv'
WITH (
    FORMAT          = 'CSV',
    FIRSTROW        = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR   = '\n',
    TABLOCK
);
GO


-- ── Step 3: Stamp score date and model version ────────────────
UPDATE loan_risk_scores
SET    score_date    = GETDATE(),
       model_version = 'GBM_v1.0'
WHERE  score_date IS NULL;
GO


-- ── Step 4: Populate monthly delinquency history ──────────────
-- Aggregates the loaded loan data into quarterly snapshots
-- used for the trend line charts on Dashboard Page 2.

INSERT INTO delinquency_history (
    snapshot_month,
    total_loans,
    delinquent_loans,
    avg_credit_score,
    total_balance,
    delinquency_rate
)
SELECT
    origination_quarter                                                    AS snapshot_month,
    COUNT(*)                                                               AS total_loans,
    SUM(CASE WHEN delinquency_status <> 'Current' THEN 1 ELSE 0 END)      AS delinquent_loans,
    ROUND(AVG(CAST(credit_score AS DECIMAL(6,2))), 2)                      AS avg_credit_score,
    SUM(loan_amount)                                                       AS total_balance,
    ROUND(
        CAST(SUM(CASE WHEN delinquency_status <> 'Current' THEN 1 ELSE 0 END) AS DECIMAL(10,4))
        / NULLIF(COUNT(*), 0), 4
    )                                                                      AS delinquency_rate
FROM loan_portfolio
GROUP BY origination_quarter
ORDER BY origination_quarter;
GO


-- ── Step 5: Verify row counts ─────────────────────────────────
SELECT 'loan_portfolio'      AS table_name, COUNT(*) AS row_count FROM loan_portfolio
UNION ALL
SELECT 'loan_risk_scores'    AS table_name, COUNT(*) AS row_count FROM loan_risk_scores
UNION ALL
SELECT 'delinquency_history' AS table_name, COUNT(*) AS row_count FROM delinquency_history;
GO


-- ── Troubleshooting ───────────────────────────────────────────
-- If BULK INSERT fails with "Cannot bulk load because the file
-- could not be opened", check the following:
--
-- 1. File path uses backslashes: C:\Projects\... not C:/Projects/...
-- 2. SQL Server service account has read permission on the folder.
--    Right-click the folder → Properties → Security → add the
--    SQL Server service account with Read permission.
-- 3. To find the service account name:
--    Services (services.msc) → SQL Server (MSSQLSERVER) → Log On As
-- 4. Alternatively, grant bulk operations permission:
--    GRANT ADMINISTER BULK OPERATIONS TO [your_login];
